services:
  mysql_student:
    image: mysql:8.0
    container_name: mysql_student_db
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: students_details
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
    volumes:
      - ./mysql_student_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - studentrecords
    healthcheck:
      test : ["CMD-SHELL","mysqladmin ping -h localhost -uadmin -pAdmin@123"]
      interval: 5s
      retries: 5
      start_period: 15s
      timeout: 5s

  backend_app:
    build:
      context: .
    container_name: django_backend_app
    restart: always
    networks:
     - studentrecords
    ports:
     - "8001:8001"
    depends_on:
      - mysql_student
    # environment:
    #   DB_HOST: mysql_student_db
    #   DB_NAME: students_details
    #   DB_USER: admin
    #   DB_PASSWORD: Admin@123
    #   DB_PORT: 3307
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8001"

networks:
  studentrecords:

volumes:
  mysql_student_data:




